name: C/C++ CI

on: [push]

jobs:
  build:

    runs-on: macos-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: Install CMake
      run:  brew install cmake
            cmake --version
    - name: CMake
      run: cmake --target all
    - name: make
      run: make -f Makefile all -j4
